export default {
  items: [
    'comment',
    'findAndReplace',
    'selectAll',
    'heading',
    '|',
    'bold',
    'italic',
    'underline',
    'removeFormat',
    'bulletedList',
    'numberedList',
    'outdent',
    'indent',
    '|',
    'undo',
    'redo',
    '-',
    'fontSize',
    'fontFamily',
    'fontColor',
    'fontBackgroundColor',
    'highlight',
    '|',
    'link',
    'insertImage',
    'blockQuote',
    'insertTable',
    '|',
    'horizontalLine',
    'pageBreak',
  ],
  shouldNotGroupWhenFull: true,
};
